Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'rest_framework'No module named 'rest_framework'

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'corsheaders'No module named 'corsheaders'

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'corsheaders'No module named 'corsheaders'

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'corsheaders'No module named 'corsheaders'

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'corsheaders'No module named 'corsheaders'

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'corsheaders'No module named 'corsheaders'

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'corsheaders'No module named 'corsheaders'

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'corsheaders'No module named 'corsheaders'

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 23, in <module>
        main()main()

  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
  File "C:\Codes\GitHub\alldesign_website\backend\manage.py", line 19, in main
        execute_from_command_line(sys.argv)execute_from_command_line(sys.argv)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
        utility.execute()utility.execute()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\management\__init__.py", line 416, in execute
        django.setup()django.setup()

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)apps.populate(settings.INSTALLED_APPS)

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\registry.py", line 91, in populate
        app_config = AppConfig.create(entry)app_config = AppConfig.create(entry)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
  File "C:\Users\DeogSeon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\apps\config.py", line 193, in create
        import_module(entry)import_module(entry)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundErrorModuleNotFoundError: : No module named 'corsheaders'No module named 'corsheaders'

